name: ESLint

on:
  push:
    branches: [master] # or [master] if that's name of the main branch
  pull_request:
    branches: [master] # or [master] if that's name of the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true

      - name: Install dependencies
        run: yarn install # or npm ci if you use npm and have the package-lock.json file

      - uses: CatChen/eslint-suggestion-action@v2
        with:
          request-changes: true # optional
          fail-check: false # optional
          github-token: ${{ secrets.GITHUB_TOKEN }} # optional
          directory: "./web" #optional
          targets: "./web" #optional
          eslint-lib-path: "./web/node_modules/eslint/lib/api.js" #optional
          eslint-bin-path: "./web/node_modules/.bin/eslint" # optional
